#! /bin/bash

rm -f redblack.log
for SIZE in 64 65536; do
  #for MODE in TRAVERSE TRAVERSEN ; do
    SCALE=$[ $SIZE*2 ]
    for UPDATE in 0 2 100 1000 10000 100000 500000 1000000; do
        for ((ii=0; ii<4; ii++)); do
            for CPUS in 16; do
            #for CPUS in {1..16}; do
            #for CPUS in 1 2 3 4 5 6 7 8 12 16 24 32 40 48 56 64; do
            #for CPUS in 1 2 4 8 16 32 64; do
                for TEST in rb_rcu rb_stm rb_rpstm rb_rpstm_rp; do
                    echo "Iteration " $ii $TEST r:$CPUS u:$UPDATE s:$SIZE S:$SCALE
                    ./$TEST m:RAND r:$CPUS s:$SIZE S:$SCALE u:$UPDATE >> redblack.log
                    who
                done
            done
        done
    done
done

awk -f decode.awk redblack.log >redblack.txt
parse redblack.txt smtrand.txt -avg

