#! /bin/bash

rm -f redblack.log
for SIZE in 64 65536; do
  for MODE in TRAVERSE TRAVERSEN ; do
    for ACCESS in READ WRITE; do
        for ((ii=0; ii<4; ii++)); do
            for CPUS in {1..16}; do
            #for CPUS in 1 2 3 4 5 6 7 8 12 16 24 32 40 48 56 64; do
            #for CPUS in 1 2 4 8 16 32 64; do
                #for TEST in rb_rcu rb_rwl_write rb_rwl_read rb_lock ccavl rpavl ; do
                for TEST in rb_rcu rb_rwl_write rb_rwl_read rb_lock ; do
                    if [ $TEST == ccavl ] ; then
                        ASYNC=1
                    else
                        ASYNC=0
                    fi
                    if [ $ACCESS == WRITE ] ; then
                        READERS=$[ $CPUS-1 ]
                        WRITERS=1
                    else
                        READERS=$CPUS
                        WRITERS=0
                    fi

                    ./$TEST m:$MODE p:$ASYNC r:$READERS w:$WRITERS s:$SIZE  >> redblack.log
                    #echo "./$TEST p:$ASYNC r:$READERS w:$WRITERS s:$SIZE"
                    echo "Iteration " $ii $TEST $CPUS $ACCESS $SIZE
                    who
                done
            done
        done
    done
  done
done

awk -f decode.awk redblack.log >redblack.txt
parse <redblack.txt >redblack_p.txt

